### ISSUE TITLE
Issue 3.1: Player Implementation

### ISSUE THREAD

**Issue by theaprox** [theaprox/card-war#10]
**Branch name:** `milestone/3-gamelogic/issue-1-player` [🔗 LINK](/theaprox/card-war/tree/milestone/3-gamelogic/issue-1-player)
<sup>used to `clone` the right branch for collaborative development</sup>

#### TODO:
- [ ] Build a Player class:
  - [ ] Properties: id, name, inventory (cards and stash)
  - [ ] Methods: draw_card, add_to_stash
  - [ ] Score calculation

> [!NOTE]
> Target files:
> `./src/actor/Player.py.py`

> [!TIP]
> See [Collab Instructions](/theaprox/card-war/blob/dev/README.md#collaboration-instructions) or contact OP *(original poster)* if you have any questions on how to proceed
