### ISSUE TITLE
Issue 4.1: CLI Interface

### ISSUE THREAD

**Issue by theaprox** [theaprox/card-war#12]
**Branch name:** `milestone/4-finale/issue-1-cli` [🔗 LINK](/theaprox/card-war/tree/milestone/4-finale/issue-1-cli)
<sup>used to `clone` the right branch for collaborative development</sup>

#### TODO:
- [ ] Implement command line interface:
  - [ ] Player name input
  - [ ] Game state display
  - [ ] Round results
  - [ ] Final score

> [!NOTE]
> Target files:
> `./war.py` (main program file)

> [!TIP]
> See [Collab Instructions](/theaprox/card-war/blob/dev/README.md#collaboration-instructions) or contact OP *(original poster)* if you have any questions on how to proceed
