### ISSUE TITLE
Issue 1.1: Base Template Implementation

### ISSUE THREAD

**Issue by theaprox** [theaprox/card-war#6]
**Branch name:** `milestone/1-core/issue-1-item-template` [🔗 LINK](/theaprox/card-war/tree/milestone/1-core/issue-1-item-template)
<sup>used to `clone` the right branch for collaborative development</sup>

#### TODO:
- [ ] Create ItemTemplate class with:
  - [ ] Properties: _id, _type, _name
  - [ ] Basic getters/setters
  - [ ] Type checking methods
- [ ] Add docstrings and type hints
- [ ] Implement basic validation

> [!NOTE]
> Target files:
> `./src/item/ItemTemplate.py`

> [!TIP]
> See [Collab Instructions](/theaprox/card-war/blob/dev/README.md#collaboration-instructions) or contact OP *(original poster)* if you have any questions on how to proceed
