### ISSUE TITLE
Issue 1.2: Container Base Classes

### ISSUE THREAD

**Issue by theaprox** [theaprox/card-war#7]
**Branch name:** `milestone/1-core/issue-2-containers` [🔗 LINK](/theaprox/card-war/tree/milestone/1-core/issue-2-containers)
<sup>used to `clone` the right branch for collaborative development</sup>

#### TODO:
- [ ] Create base Inventory class:
  - [ ] Methods: add, remove, get
  - [ ] Type validation
  - [ ] Basic error handling
- [ ] Create PlayerInventory class:
  - [ ] Extend base Inventory
  - [ ] Implement play stack container
  - [ ] Implement stash container

> [!NOTE]
> Target files:
> `./src/itemcontainer/Inventory.py`
> `./src/itemcontainer/PlayerInventory.py`

> [!TIP]
> See [Collab Instructions](/theaprox/card-war/blob/dev/README.md#collaboration-instructions) or contact OP *(original poster)* if you have any questions on how to proceed
