### ISSUE TITLE
Issue 2.2: Deck Implementation

### ISSUE THREAD

**Issue by theaprox** [theaprox/card-war#9]
**Branch name:** `milestone/2-components/issue-2-deck` [🔗 LINK](/theaprox/card-war/tree/milestone/2-components/issue-2-deck)
<sup>used to `clone` the right branch for collaborative development</sup>

#### TODO:
- [x] Create Deck class:
  - [x] Generate 32-card deck
  - [x] Shuffle method
  - [x] Deal method
- [x] Add validation for card uniqueness

> [!NOTE]
> Target files:
> `./src/item/Deck.py`

> [!TIP]
> See [Collab Instructions](/theaprox/card-war/blob/dev/README.md#collaboration-instructions) or contact OP *(original poster)* if you have any questions on how to proceed
